### ISSUE TITLE
question: What is the motivation for using duplexed SSE rather than WebSocket?

### ISSUE THREAD

**Issue by viglucci** [WebReflection/bidi-sse#1]
Hi all,

First I would like to say that this is a very interesting package.

Without having a ton of context on why this package was developed or how it came about, I was hoping you might be able to explain the motivations for wanting to leverage SSE in a duplexed way, rather than using WebSockets?

Thanks

**Comment by WebReflection** [comment]
Easy answer here:
https://github.com/WebReflection/proxied-node/issues/1

That’s why this module exists

**Comment by WebReflection** [comment]
Closing as no issue, but feel free to discuss anything you like 👍
